language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
#  - osx
sudo: required
dist: trusty
script:
  - $CXX -O3 -std=c++11 bin2c.cpp -o "bin2c"
  - chmod u+x ./bin2c
  - chmod u+x ./tests/VP.jpg
  - ./bin2c /custvar "IMAGE_VP" /nohead /infile "./tests/VP.jpg" /outfile "./tests/VP.hpp" /basefolder "./tests/"
  - $CXX -O3 -std=c++11 ./tests/VP.cpp -o ./tests/VP
env:
  global:
   - secure: "dCRZoMHNI3Qg/D8FrCzSKQ1zsPVgxMZCXSbuTsBXzcVcN6ujF3Q1UnycsMpOOu/QYItFQX3dOg0UrrV3RmUooBGLeW5h3H4RQvYs4/UXg3PgDOjcaLXIJJHb8ijapQphnkjZt4vS1fCVM0i/X6tQwhbEIseswoe8sOTVb1JTyE6zyMEwLGESpn1v/RMQOgFMqaF6PZfYRkXDx+kANoaFx+H4coCElwP0ikqZLbklDKgCEgqAgkMXQQGpeVGfEkn07heOtwqyTJHKdSV2/01ZbAVpzukRYx7e7pXT5ZZdGrcb+1oEGZMyUIUX2nGmc+7NnuwZSTPmSJFiTIP1ars35gIE712pIYI0Vap+XjIc0/+30S9aZitwQUgQ/6yMPpHjPMjOCWM/5wf9+LPL6U1bj+jQFt2KJz+gUo11VL+6S1+4kVCNv+dgyn4eR0+pBNLiFLleTLRzH8q1h9Wze7NnymH/mZfU0LHz/P+Fd/500J9XwU65eEwWAiH+LbRk6RtBH0FbQK3C+V7itYOcScHsV8Gt/EMyepkhdG37cT+xXwxq8b8xA3c3cnQnTR7F4nSl1KO7CbBs4UKM3oeKv5iYSEop6uJmIo1fDtMpDVcDoNz1n55KwMjvXoxx5oS7x0Z2gvi9oOGl6NLnXVfNDbYtNxQI1q5NCORfv9BuX7s2fbc="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "AraHaan/bin2c"
      version: 0.12.0
      description: "bin2c Conversion Tool."
    notification_email: seandhunt_7@yahoo.com
    build_command_prepend: $CXX "-O3 -std=c++11 ./bin2c.cpp -o ./bin2c"
    build_command: $CXX "-O3 -std=c++11 ./bin2c.cpp -o ./bin2c"
    branch_pattern: coverity_scan
