language: cpp
sudo: required
dist: trusty

# addons:
#   coverity_scan:
#     project:
#       name: "AraHaan/bin2c"
#       version: 0.15.0
#       description: "bin2c Conversion Tool."
#
#     apt:
#         sources:
#             - ubuntu-toolchain-r-test
#             - llvm-toolchain-precise-3.9
#         packages:
#             - g++-6
#             - clang-3.9
#
#     notification_email: seandhunt_7@yahoo.com
#    build_command_prepend: " -O3 -std=c++14 bin2c.cpp -o bin2c"
#    build_command: $CXX
#    branch_pattern: coverity_scan

notifications:
  email:
    on_success: always
    on_failure: never

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CCC=gcc-5 && CXXX=g++-5 && FSLIB=-lstdc++fs && CPPLIB="

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CCC=gcc-6 && CXXX=g++-6 && FSLIB=-lstdc++fs && CPPLIB="

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CCC=gcc-7 && CXXX=g++-7 && FSLIB=-lstdc++fs && CPPLIB="

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - clang-3.9
      env:
        - MATRIX_EVAL="CCC=clang-3.9 && CXXX=clang++-3.9 && FSLIB=-lc++experimental && CPPLIB=-stdlib=libc++"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - clang-4.0
      env:
        - MATRIX_EVAL="CCC=clang-4.0 && CXXX=clang++-4.0 && FSLIB=-lc++experimental && CPPLIB=-stdlib=libc++"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-5.0
      env:
        - MATRIX_EVAL="CCC=clang-5.0 && CXXX=clang++-5.0 && FSLIB=-lc++experimental && CPPLIB=-stdlib=libc++"

  allow_failures:
    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="brew install gcc5 && CCC=gcc-5 && CXXX=g++-5 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="brew install gcc6 && CCC=gcc-6 && CXXX=g++-6 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode8.3
      env:
        - MATRIX_EVAL="brew install gcc && CCC=gcc-7 && CXXX=g++-7 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew install gcc5 && CCC=gcc-5 && CXXX=g++-5 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew install gcc6 && CCC=gcc-6 && CXXX=g++-6 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew install gcc && CCC=gcc-7 && CXXX=g++-7 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="brew install gcc5 && CCC=gcc-5 && CXXX=g++-5 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="brew install gcc6 && CCC=gcc-6 && CXXX=g++-6 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="brew install gcc && CCC=gcc-7 && CXXX=g++-7 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="brew install gcc5 && CCC=gcc-5 && CXXX=g++-5 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="brew install gcc6 && CCC=gcc-6 && CXXX=g++-6 && FSLIB=-lstdc++fs && CPPLIB="

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="brew install gcc && CCC=gcc-7 && CXXX=g++-7 && FSLIB=-lstdc++fs && CPPLIB="

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - $CXXX -O3 -std=c++14 bin2c.cpp $CPPLIB $FSLIB -o "bin2c"

after_success:
  - chmod u+x ./bin2c
  - chmod u+x ./tests/VP.jpg
  - ./bin2c /custvar "IMAGE_VP" /nohead /infile "./tests/VP.jpg" /outfile "./tests/VP.hpp" /basefolder "./tests/"
  - $CXXX -O3 -std=c++14 $CPPLIB ./tests/VP.cpp -o ./tests/VP
  - chmod u+x ./tests/VP

#env:
#  global:
#   - secure: "dCRZoMHNI3Qg/D8FrCzSKQ1zsPVgxMZCXSbuTsBXzcVcN6ujF3Q1UnycsMpOOu/QYItFQX3dOg0UrrV3RmUooBGLeW5h3H4RQvYs4/UXg3PgDOjcaLXIJJHb8ijapQphnkjZt4vS1fCVM0i/X6tQwhbEIseswoe8sOTVb1JTyE6zyMEwLGESpn1v/RMQOgFMqaF6PZfYRkXDx+kANoaFx+H4coCElwP0ikqZLbklDKgCEgqAgkMXQQGpeVGfEkn07heOtwqyTJHKdSV2/01ZbAVpzukRYx7e7pXT5ZZdGrcb+1oEGZMyUIUX2nGmc+7NnuwZSTPmSJFiTIP1ars35gIE712pIYI0Vap+XjIc0/+30S9aZitwQUgQ/6yMPpHjPMjOCWM/5wf9+LPL6U1bj+jQFt2KJz+gUo11VL+6S1+4kVCNv+dgyn4eR0+pBNLiFLleTLRzH8q1h9Wze7NnymH/mZfU0LHz/P+Fd/500J9XwU65eEwWAiH+LbRk6RtBH0FbQK3C+V7itYOcScHsV8Gt/EMyepkhdG37cT+xXwxq8b8xA3c3cnQnTR7F4nSl1KO7CbBs4UKM3oeKv5iYSEop6uJmIo1fDtMpDVcDoNz1n55KwMjvXoxx5oS7x0Z2gvi9oOGl6NLnXVfNDbYtNxQI1q5NCORfv9BuX7s2fbc="

