name: C/C++ CI (Ubuntu clang)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Compiler check
      run: clang++ --version
    - name: Compile
      run: make
      env:
        CXX: clang++
        
    - name: Tests
      run: make test
      env:
        CXX: clang++
