name: C/C++ CI (Ubuntu)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Compiler check
      run: g++ --version
    - name: Compile
      run: g++ -O3 -std=c++14 bin2c.cpp -lstdc++fs -o ./bin2c
    - name: Permission changes.
      run: >-
        chmod u+x ./bin2c

        chmod u+x ./tests/VP.jpg

    - name: Tests
      run: >-
        ./bin2c /custvar "IMAGE_VP" /nohead /infile "./tests/VP.jpg" /outfile "./tests/VP.hpp" /basefolder "./tests/"

        g++ -O3 -std=c++14 "./tests/VP.cpp" -o "./tests/VP"
