name: C/C++ CI (Mac OSX clang)

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Compiler check
      run: clang++ --version
    - name: Compile and Install.
      run: >-
        cd MAC

        make install
      env:
        CXX: clang++

    - name: Tests
      run: >-
        cd MAC

        make test

    - name: Uninstall and clean build.
      run: >-
        cd MAC

        make uninstall

        make clean
