name: C/C++ CI (Windows x86)

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Compile
      run: msbuild "bin2c.sln" /m /verbosity:minimal
      env:
        Platform: x86
    - name: Tests
      run: >-
        Release/x86/bin2c /custvar "IMAGE_VP" /nohead /infile "./tests/VP.jpg" /outfile "./tests/VP.hpp" /basefolder "./tests/"
        
        msbuild "tests/VP.sln"
